apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erlmcp-dev

resources:
  - ../../base

images:
  - name: erlmcp
    newName: ghcr.io/seanchatmangpt/erlmcp
    newTag: main

replicas:
  - name: erlmcp
    count: 1

configMapGenerator:
  - name: erlmcp-config
    behavior: merge
    literals:
      - ERLMCP_LOG_LEVEL=debug
      - ERLMCP_SESSION_BACKEND=ets
      - ERLMCP_REGISTRY_TYPE=local

patchesStrategicMerge:
  - patches/statefulset-dev.yaml
